FROM openjdk:17-jdk-slim

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

RUN chmod +x mvnw && ./mvnw dependency:go-offline

COPY . .

RUN ./mvnw clean package -DskipTests

CMD ["java", "-jar", "target/management-0.0.1-SNAPSHOT.jar"]
